org: norbesc
app: reto-norbesc
service: reto-api

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1 
  

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
          Resource:
            - Fn::GetAtt: [FilmTable, Arn]

plugins:
  - serverless-auto-swagger

functions:
  app:
    handler: src/app.welcome
    events:
      - httpApi:
          path: /api
          method: get

  GetFilm:
    handler: src/lambda/starWars/index.handler 
    # Este handler no expone un endpoint HTTP, se invoca desde otras funciones Lambda

  people:
    handler: src/controllers/people.handler
    events:
      - httpApi:
          path: /api/getPeople
          method: get
 
  addFilm:
    handler: src/controllers/addFilm.handler
    events:
      - http:
          path: /api/createFill
          method: post
  getFilmsDB:
    handler: src/controllers/getFilm.handler
    events:
      - httpApi:
          path: /api/getFilmsById/{id}
          method: get

resources:
  Resources:
    FilmTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: FilmTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

custom:
  documentation:
    api:
      info:
        title: Reto API
        version: 1.0.0
    models:
      - name: Film
        description: A film resource
        type: object
        required:
          - id
          - email
          - title
          - director
          - producer
        properties:
          id:
            type: string
          email:
            type: string  
          title:
            type: string
          director:

            type: string
          producer:
            type: string
    operations:
      - path: /api
        method: get
        summary: Get  message to welcome
        description: Retrieves a simple welcome message
        responses:
          '200':
            description: Successful response
            schema:
              $ref: '#/models/Film'
      - path: /api/getPeople
        method: get
        summary: Get a list of people
        description: Retrieves a list of people
        responses:
          '200':
            description: Successful response
            schema:
              type: array
              items:
                $ref: '#/models/Film'
      - path: /api/getFilm
        method: get
        summary: Get a film
        description: Retrieves a film
        responses:
          '200':
            description: Successful response
            schema:
              $ref: '#/models/Film'
      - path: /api/createFill
        method: post
        summary: Create a film
        description: Creates a new film
        requestBody:
          description: The film to create
          required: true
          schema:
            $ref: '#/components/schemas/Film'
        responses:
          '200':
            description: Successful response
            schema: 
              Film:
                type: object
                properties:
                  id:
                    type: string
                  title:
                    type: string
                  producer:
                    type: string
                  director:
                    type: string
                  createdAt:
                    type: integer
                  done:
                    type: boolean
      - path: /api/getFilmsById/{id}
        method: get
        summary: Get a film by ID
        description: Retrieves a film by its ID
        parameters:
          - name: id
            in: path
            required: true
            schema:
              type: string
        responses:
          '200':
            description: Successful response
            schema:
              $ref: '#/models/Film'
 