# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: norbesc
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: reto-norbesc
# "service" is the name of this project. This will also be added to your AWS resource names.
service: reto-api
 
provider:
  name: aws
  runtime: nodejs20.x  

functions:
  hello:
    handler: src/hello.hello
    events:
      - httpApi:
          path: /
          method: get
  people:
    handler: src/people.people
    events:
      - httpApi:
          path: /getPeople
          method: get  
  films:
    handler: src/films.films
    events:
      - httpApi:
          path: /getFilm
          method: get                
 