// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "reto-api",
    "version": "1"
  },
  "paths": {
    "/api": {
      "get": {
        "summary": "app",
        "description": "",
        "operationId": "app.get./api",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/api/getPeople": {
      "get": {
        "summary": "people",
        "description": "",
        "operationId": "people.get./api/getPeople",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/api/getFilm": {
      "get": {
        "summary": "films",
        "description": "",
        "operationId": "films.get./api/getFilm",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/api/createFill": {
      "post": {
        "summary": "addFilm",
        "description": "",
        "operationId": "addFilm.post./api/createFill",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/api/getFilmsById/{id}": {
      "get": {
        "summary": "getFilmsDB",
        "description": "",
        "operationId": "getFilmsDB.get./api/getFilmsById/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    }
  },
  "definitions": {
    "Film": {
      "properties": {
        "id": {
          "title": "Film.id",
          "type": "string"
        },
        "title": {
          "title": "Film.title",
          "type": "string"
        },
        "director": {
          "title": "Film.director",
          "type": "string"
        },
        "producer": {
          "title": "Film.producer",
          "type": "string"
        }
      },
      "required": [
        "id",
        "title",
        "director",
        "producer"
      ],
      "additionalProperties": false,
      "title": "Film",
      "type": "object"
    },
    "Films": {
      "properties": {
        "titulo": {
          "title": "Films.titulo",
          "type": "string"
        },
        "director": {
          "title": "Films.director",
          "type": "string"
        },
        "productor": {
          "title": "Films.productor",
          "type": "string"
        },
        "fecha_estreno": {
          "title": "Films.fecha_estreno",
          "type": "string"
        }
      },
      "required": [
        "titulo",
        "director",
        "productor",
        "fecha_estreno"
      ],
      "additionalProperties": false,
      "title": "Films",
      "type": "object"
    },
    "APIGatewayProxyResult": {
      "properties": {
        "statusCode": {
          "title": "APIGatewayProxyResult.statusCode",
          "type": "number"
        },
        "body": {
          "title": "APIGatewayProxyResult.body",
          "type": "string"
        }
      },
      "required": [
        "statusCode",
        "body"
      ],
      "additionalProperties": false,
      "title": "APIGatewayProxyResult",
      "type": "object"
    },
    "APIGatewayProxyEvent": {
      "additionalProperties": {},
      "title": "APIGatewayProxyEvent",
      "type": "object"
    },
    "FilmResponse": {
      "properties": {
        "success": {
          "title": "FilmResponse.success",
          "type": "boolean"
        },
        "data": {
          "$ref": "#/definitions/%C3%A4ny",
          "title": "FilmResponse.data"
        },
        "message": {
          "title": "FilmResponse.message",
          "type": "string"
        }
      },
      "required": [
        "success",
        "data",
        "message"
      ],
      "additionalProperties": false,
      "title": "FilmResponse",
      "type": "object"
    },
    "GetFilmResponse": {
      "properties": {
        "film": {
          "$ref": "#/definitions/Film",
          "title": "GetFilmResponse.film"
        }
      },
      "required": [
        "film"
      ],
      "additionalProperties": false,
      "title": "GetFilmResponse",
      "type": "object"
    },
    "GetFilmsResponse": {
      "properties": {
        "films": {
          "items": {
            "$ref": "#/definitions/Film",
            "title": "GetFilmsResponse.films.[]"
          },
          "title": "GetFilmsResponse.films",
          "type": "array"
        }
      },
      "required": [
        "films"
      ],
      "additionalProperties": false,
      "title": "GetFilmsResponse",
      "type": "object"
    },
    "CreateFilmRequest": {
      "properties": {
        "film": {
          "$ref": "#/definitions/Film",
          "title": "CreateFilmRequest.film"
        }
      },
      "required": [
        "film"
      ],
      "additionalProperties": false,
      "title": "CreateFilmRequest",
      "type": "object"
    },
    "CreateFilmResponse": {
      "properties": {
        "film": {
          "$ref": "#/definitions/Film",
          "title": "CreateFilmResponse.film"
        }
      },
      "required": [
        "film"
      ],
      "additionalProperties": false,
      "title": "CreateFilmResponse",
      "type": "object"
    }
  },
  "securityDefinitions": {}
};